"""
Phase 5 deployment generation: store page copy, press kit, Unity build guides,
and the export bundle. The export bundle aggregates existing data (GDD +
assets) — no LLM call.
"""
import base64
import io
import json
import re
import zipfile

from app.models.assets import UnityGuide
from app.prompts.deployment_prompts import (
    STORE_PAGE_SYSTEM_PROMPT,
    PRESS_KIT_SYSTEM_PROMPT,
    BUILD_GUIDE_SYSTEM_PROMPT,
    build_store_page_prompt,
    build_press_kit_prompt,
    build_build_guide_prompt,
)
from app.services.llm_utils import complete, extract_json


async def generate_store_page(platform: str, game_context: str) -> dict:
    data = extract_json(
        await complete(STORE_PAGE_SYSTEM_PROMPT, build_store_page_prompt(platform, game_context))
    )
    title = str(data.get("title", "")).strip()
    if not title:
        raise ValueError("LLM returned no store page title")
    return {
        "title": title,
        "short_description": str(data.get("shortDescription", "")).strip(),
        "long_description": str(data.get("longDescription", "")).strip(),
        "tags": [str(t) for t in data.get("tags", [])],
        "bullets": [str(b) for b in data.get("bullets", [])],
    }


async def generate_press_kit(game_context: str) -> dict:
    data = extract_json(await complete(PRESS_KIT_SYSTEM_PROMPT, build_press_kit_prompt(game_context)))
    tagline = str(data.get("tagline", "")).strip()
    if not tagline:
        raise ValueError("LLM returned no press kit tagline")
    return {
        "tagline": tagline,
        "description": str(data.get("description", "")).strip(),
        "key_features": [str(f) for f in data.get("keyFeatures", [])],
        "dev_blurb": str(data.get("devBlurb", "")).strip(),
    }


async def generate_build_guide(platform: str, title: str) -> UnityGuide:
    data = extract_json(
        await complete(BUILD_GUIDE_SYSTEM_PROMPT, build_build_guide_prompt(platform, title))
    )
    steps = [str(s) for s in data.get("steps", [])]
    if not steps:
        raise ValueError("LLM returned no build guide steps")
    return UnityGuide(steps=steps, completed=[False] * len(steps))


def safe_filename(name: str, fallback: str = "file") -> str:
    """Strip path separators/traversal sequences so a name can't escape its zip folder."""
    name = re.sub(r"[/\\]", "_", name).replace("..", "_")
    name = re.sub(r"[^A-Za-z0-9._ -]", "", name).strip().strip(".")
    return name or fallback


def _gdd_to_markdown(title: str, sections: dict) -> str:
    parts = [f"# {title} — GDD\n"]
    for key, body in sections.items():
        parts.append(f"## {key.capitalize()}\n\n{body or ''}\n")
    return "\n".join(parts)


def _readme_text(title: str, assets: list[dict]) -> str:
    lines = [f"# {title} — Game Bundle\n", "Generated by GameGold.\n"]
    if not assets:
        lines.append("No assets were generated yet.\n")
    for asset in assets:
        guide = asset.get("unity_guide") or {}
        steps = guide.get("steps", [])
        lines.append(f"## {asset.get('type')}: {asset.get('name')}\n")
        for i, step in enumerate(steps, start=1):
            lines.append(f"{i}. {step}")
        lines.append("")
    return "\n".join(lines)


async def export_project_bundle(db, project_id: str, title: str) -> bytes:
    gdd = await db.gdds.find_one({"project_id": project_id})
    sections = gdd.get("sections", {}) if gdd else {}

    cursor = db.assets.find({"project_id": project_id})
    assets = await cursor.to_list(500)

    buffer = io.BytesIO()
    with zipfile.ZipFile(buffer, "w", zipfile.ZIP_DEFLATED) as zf:
        zf.writestr("GDD.md", _gdd_to_markdown(title, sections))
        zf.writestr("README.md", _readme_text(title, assets))

        for asset in assets:
            name = safe_filename(str(asset.get("name", "asset")).replace(" ", "_"))
            asset_type = asset.get("type")
            if asset_type == "script" and asset.get("code"):
                zf.writestr(f"Scripts/{name}.cs", asset["code"])
            elif asset_type == "sprite" and asset.get("url"):
                url = asset["url"]
                if url.startswith("data:") and "base64," in url:
                    encoded = url.split("base64,", 1)[1]
                    zf.writestr(f"Sprites/{name}.png", base64.b64decode(encoded))
            elif asset_type == "dialogue" and asset.get("tree"):
                zf.writestr(f"Dialogue/{name}.json", json.dumps(asset["tree"], indent=2))

    return buffer.getvalue()
